const birdsData = [
  {
    id: 1,
    Common_Name: "Black-capped Chickadee",
    Scientific_Name: "Poecile atricapillus",
    Type: "Common",
    Season: "Year-round",
    Fact: "Famous for its distinctive 'chick-a-dee-dee-dee' call.",
    Call: "Call: quick 'chick-a-dee-dee' chatter; song is a clear two-note 'fee-bee'.",
    Whistle: "Whistle tip: play a clean two-note 'fee-bee' with the second note slightly lower; add short, choppy bursts for the chatter.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVsgFltlwCxanuJIS8Q9dvxx4qdllwjLGuT7tfkS7HsP-Hl19F1tHin3x7B0h3IFuzyxmvxX9VCIX-4verEf0iMr38KbCDQytzosvQGZh6&s=10"
  },
  {
    id: 2,
    Common_Name: "American Robin",
    Scientific_Name: "Turdus migratorius",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "Often seen pulling earthworms from the ground.",
    Call: "Call: cheery, repeated phrases often rendered as 'cheerily, cheer-up, cheerio'.",
    Whistle: "Whistle tip: play 3–5 bright phrases with tiny pauses between, slightly rising at the end of each phrase.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZrU2lR6V86zMHpXRD32DTjwfqNk-ZkNsZcDBniLtx-DxyV_0C6-xV_v8aaKAL0xi1CrZZZPuwUHFMno14bhZ_YNR38nKMFs18w5y0PGn8_w&s=10"
  },
  {
    id: 3,
    Common_Name: "House Sparrow",
    Scientific_Name: "Passer domesticus",
    Type: "Common",
    Season: "Year-round",
    Fact: "Aggressive and adaptable, found near humans.",
    Call: "Call: simple 'cheep' and 'chirrup' notes in quick bursts.",
    Whistle: "Whistle tip: use short, repeated chirps with small pitch hops—think fast, casual chatter.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSenVyTPz6B9-QT3sTfnlHph2ppJPbrNAkv0Xsn2Yt7H9FH1xja7yfCOr33i-E0f9DcCQnJYP3hIoDaihVP3CFGHnvPnYWgLNCuRA2dppq9VA&s=10"
  },
  {
    id: 4,
    Common_Name: "Blue Jay",
    Scientific_Name: "Cyanocitta cristata",
    Type: "Common",
    Season: "Year-round",
    Fact: "Known for their intelligence and loud screams.",
    Call: "Call: loud 'jay-jay' screams with occasional clear whistles like 'tool-a'.",
    Whistle: "Whistle tip: blow a strong, slightly descending 'jay' note; add a clean, fluty two-note whistle for variety.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR64uqTayxH-cwSdZNY21Y2k_HFUAVN1WvLwAKd3IpRDmfowfpx6gOWlhdgcPhAUfo8JZ2coNjZ8mYwaipd1owC_CZaR05FUNiqX43nu0XAkw&s=10"
  },
  {
    id: 5,
    Common_Name: "Canada Goose",
    Scientific_Name: "Branta canadensis",
    Type: "Common",
    Season: "Spring/Fall",
    Fact: "Famous for flying in a V-formation.",
    Call: "Call: deep, resonant 'honk' notes, often in pairs.",
    Whistle: "Whistle tip: use a fuller breath and longer tone to mimic a 'honk-honk' pattern, spacing the notes evenly.",
    Image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Canada_goose_on_Seedskadee_NWR_%2827826185489%29.jpg"
  },
  {
    id: 6,
    Common_Name: "Mallard Duck",
    Scientific_Name: "Anas platyrhynchos",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "The ancestor of most domestic ducks.",
    Call: "Call: classic quacks—short, nasal notes, sometimes in a series.",
    Whistle: "Whistle tip: play short, rounded 'quack' bursts, then taper off into softer notes for a flock-like feel.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScgmTtBWxyk66TGra6jnTL1rAK1wGvgwr0qA&s"
  },
  {
    id: 7,
    Common_Name: "Downy Woodpecker",
    Scientific_Name: "Dryobates pubescens",
    Type: "Common",
    Season: "Year-round",
    Fact: "Uses its stiff tail feathers for support against trees.",
    Call: "Call: sharp 'pik' notes and a short, accelerating rattle.",
    Whistle: "Whistle tip: make crisp, single 'pik' notes, then a quick staccato roll to suggest drumming.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ98bBVGDaapiA8GuDppHTN59hpNjgRp47mLpDXPRJFJ40zoWDk8ADbJwXJL6nW5iaXomhySiofI69PqlRo2Ex61QZY7HyXqUzW7vlozw&s=10"
  },
  {
    id: 8,
    Common_Name: "European Starling",
    Scientific_Name: "Sturnus vulgaris",
    Type: "Common",
    Season: "Year-round",
    Fact: "Can mimic the sounds of other birds and alarms.",
    Call: "Call: varied whistles, clicks, and warbles with mimicry mixed in.",
    Whistle: "Whistle tip: string together varied, sliding notes—mix bright whistles with quick trills to sound mimicking.",
    Image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Toulouse_-_Sturnus_vulgaris_-_2012-02-26_-_3.jpg/500px-Toulouse_-_Sturnus_vulgaris_-_2012-02-26_-_3.jpg"
  },
  {
    id: 9,
    Common_Name: "Red-winged Blackbird",
    Scientific_Name: "Agelaius phoeniceus",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "Fiercely defends nests, even against humans.",
    Call: "Call: a sharp 'conk-la-ree' with a rising, buzzy trill at the end.",
    Whistle: "Whistle tip: start with a short low note, then finish with a brighter, rising trill.",
    Image: "https://gardenandgun.com/wp-content/uploads/2025/01/AdobeStock_319024362-1100x733.jpeg"
  },
  {
    id: 10,
    Common_Name: "Northern Cardinal",
    Scientific_Name: "Cardinalis cardinalis",
    Type: "Common",
    Season: "Year-round",
    Fact: "Males are bright red; females are pale brown.",
    Call: "Call: clear, repeated whistles often rendered as 'cheer-cheer-cheer' or 'birdie-birdie'.",
    Whistle: "Whistle tip: play clean, even whistles in sets of two or three, slightly rising in pitch.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNr0I2WaLAafJ86hvQKC-33uSIf8VVplBAJpJqwYHFaR0GrLo5qb8X89Ojb9h_dydaIZWzg-eHBt7llgWLWyy2shnhOZZ-XVSKoO9kmOW57w&s=10"
  },
  {
    id: 11,
    Common_Name: "Common Grackle",
    Scientific_Name: "Quiscalus quiscula",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "Known for iridescent bodies and golden eyes.",
    Call: "Call: harsh, metallic 'chack' and squeaky hinge-like notes.",
    Whistle: "Whistle tip: use a raspier tone, then add a quick upward squeak to mimic the hinge sound.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST1BMcECDYex56Q7QBEZ9XJ4TPZ5DCp_OKcCGnIvsS9mOFjPi_eI4mZWymI5Kn8gOGfEDYZMe2pET9-s7gXcu0bKRRSLiocppDh7R1xsA_&s=10"
  },
  {
    id: 12,
    Common_Name: "Mourning Dove",
    Scientific_Name: "Zenaida macroura",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "Their wings make a whistling sound when taking off.",
    Call: "Call: soft, plaintive coo 'coo-OO-oo' in a three-part rhythm.",
    Whistle: "Whistle tip: play three gentle notes—middle note higher—then let the last fade softly.",
    Image: "https://www.generalpest-ohio.com/wp-content/uploads/mourning-dove.webp"
  },
  {
    id: 13,
    Common_Name: "American Crow",
    Scientific_Name: "Corvus brachyrhynchos",
    Type: "Common",
    Season: "Year-round",
    Fact: "Incredibly intelligent and can solve puzzles.",
    Call: "Call: classic, throaty 'caw' notes, often in sets of two to four.",
    Whistle: "Whistle tip: use a strong, open tone and repeat in even pairs to suggest the crow cadence.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv2V-HBrzAIwpIujk-IHl0oD309SN7XWeNPg&s"
  },
  {
    id: 14,
    Common_Name: "White-breasted Nuthatch",
    Scientific_Name: "Sitta carolinensis",
    Type: "Common",
    Season: "Year-round",
    Fact: "Often climbs down tree trunks head-first.",
    Call: "Call: nasal, honking 'yank-yank' notes.",
    Whistle: "Whistle tip: make short, slightly nasal-sounding notes in steady pairs.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgAZxMdo4Xmf_EYpFYuxuXpaMne0xjVR8rNklpXDelX4rKKJyjM0nNMxl3EyzjPEifWH0-QFdDD57IzqD0CkFVDBfEV_qGZI090EouW5on&s=10"
  },
  {
    id: 15,
    Common_Name: "Dark-eyed Junco",
    Scientific_Name: "Junco hyemalis",
    Type: "Common",
    Season: "Winter",
    Fact: "Nicknamed 'Snowbirds' as they appear in winter.",
    Call: "Call: light, trilling songs and soft 'tick' notes.",
    Whistle: "Whistle tip: hold a steady pitch and flutter the airflow to create a gentle trill.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU06ghOnDLBoQeWe56daUQrlHKgkmpYJzdVbdbG7a_Un9xtt3NNmisLILNvT8N-O_DK1GvXiYkkhYpTN_PPtqIYCvDeI-e_bqC006IBw&s=10"
  },
  {
    id: 16,
    Common_Name: "Boreal Chickadee",
    Scientific_Name: "Poecile hudsonicus",
    Type: "Common",
    Season: "Year-round",
    Fact: "Hardier than its black-capped cousin.",
    Call: "Call: soft chickadee chatter with a thin, clear whistle.",
    Whistle: "Whistle tip: use a lighter, breathier 'chick' burst, then a simple two-note whistle.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1PL0X2jZN2n6W4zs0eGFVOEWjx1L0kwYo-SIPlJkOVT2Cq5YNiXJlHqpcCtQjAb-mPjZ9yM2X-dbxP4Fz6WcMoNTnyFIwG2qScwhA7X4&s=10"
  },
  {
    id: 17,
    Common_Name: "Chipping Sparrow",
    Scientific_Name: "Spizella passerina",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "Has a distinct rusty cap and a trilling song.",
    Call: "Call: dry, mechanical trill that stays on one pitch.",
    Whistle: "Whistle tip: keep one steady note and flutter your tongue or breath for a fast, even trill.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCZjvzJDHumOwx8q2EhO95FP3gHAC4fP4n0hYxMsc9H48UUaS1jRvyNCvVFg57_uhYYSlQRsUG3Qb1VCaiwJSEAf796PaNs-MhS-v4vHk&s=10"
  },
  {
    id: 18,
    Common_Name: "Baltimore Oriole",
    Scientific_Name: "Icterus galbula",
    Type: "Common",
    Season: "Spring/Summer",
    Fact: "Weaves intricate hanging bag nests.",
    Call: "Call: rich, fluty whistles in short, musical phrases.",
    Whistle: "Whistle tip: play clear, bell-like whistles with small pauses—think simple, melodic phrases.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxyplzztyefcvZjbSbKYeC0wqGea3ROfQKtpc27XCDwKeZrdOmJ1zFAQxm6cOIsyDBW0Ay0G4JJ_NrQSuBFEpAOafogEvs612YtIbNmqA&s=10"
  },
  {
    id: 19,
    Common_Name: "Ruby-throated Hummingbird",
    Scientific_Name: "Archilochus colubris",
    Type: "Common",
    Season: "Summer",
    Fact: "The only hummingbird that breeds in eastern North America.",
    Call: "Call: tiny, high-pitched 'chip' or 'squeak' notes.",
    Whistle: "Whistle tip: use very short, high notes—light and quick, like tiny peeps.",
    Image: "https://media.audubon.org/2025-05/Aud_APA-2019_Ruby-throated-Hummingbird_P1_8054-5_Photo-Steven-Biegler-sq-2.jpg?width=808&auto=webp&quality=90&fit=bounds&disable=upscale"
  },
  {
    id: 20,
    Common_Name: "Great Grey Owl",
    Scientific_Name: "Strix nebulosa",
    Type: "Common",
    Season: "Year-round",
    Fact: "Manitoba's Provincial Bird. The largest owl by length.",
    Call: "Call: deep, low 'whoo' notes spaced evenly.",
    Whistle: "Whistle tip: aim for the lowest whistle pitch you can, slow and resonant in a steady rhythm.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPpQSsofMb7tccBZy3XMhot5sGYvBuJFKSqwQkIAYCcyfcrJMf3BbPHqDRpLx2DgE-cVjI1aP9wk8bvbnrRp9k_wnCapzY_VDKW9eXJg&s=10"
  },
  {
    id: 21,
    Common_Name: "Warbling Vireo",
    Scientific_Name: "Vireo gilvus",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Known for a long, complex, warbling song.",
    Call: "Call: continuous warble of short, sweet phrases that tumble together.",
    Whistle: "Whistle tip: chain together several short whistles without long pauses, gently rising and falling.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAp7lL6cRwGhNwwHdCAOtegp-sy8d5lj8yXIa2pSZ7s80SEDW5VfKClmChiT3KCwtIPDGxF9j0gHjdr8b4HXiiu36cBQVFFA2D0L7dwA&s=10"
  },
  {
    id: 22,
    Common_Name: "Piping Plover",
    Scientific_Name: "Charadrius melodus",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Endangered shorebird nesting on sandy beaches.",
    Call: "Call: a clear, thin 'peep-lo' or 'peep' whistle.",
    Whistle: "Whistle tip: play a bright two-note whistle with a slightly lower second note.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGYELpcSXhASn_DygAzzyR5Htr3nygTeyNeqwrKU-AVUGO742PZHxu4cF5z6oMrYS07d9lIUk-_ek__2J8neePlTvcWvpPg54ln4HTeg&s=10"
  },
  {
    id: 23,
    Common_Name: "Loggerhead Shrike",
    Scientific_Name: "Lanius ludovicianus",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Impales prey on thorns or barbed wire.",
    Call: "Call: sharp, high 'shree' notes and harsh chatter.",
    Whistle: "Whistle tip: blow a piercing, slightly downward-slurred note, then add a brief chatter.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWmJFMo8G3calUH_l549S-aQWGCj_uGsCs0eq-DvwjzSwuBxEcLdNs3pacV1kFJkQR7EMORb17FDA9LX-lrbwc8hx2mIe2Z2EeBu8leYg&s=10"
  },
  {
    id: 24,
    Common_Name: "Eared Grebe",
    Scientific_Name: "Podiceps nigricollis",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Has golden 'ears' (feathers) behind its eyes.",
    Call: "Call: thin, squeaky whistles and short 'whit' notes.",
    Whistle: "Whistle tip: use quick, thin whistles in pairs to mimic the clipped calls.",
    Image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Black-necked_Grebe_Schwarzhalstaucher.jpg/1280px-Black-necked_Grebe_Schwarzhalstaucher.jpg"
  },
  {
    id: 25,
    Common_Name: "Western Meadowlark",
    Scientific_Name: "Sturnella neglecta",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Known for its beautiful, flute-like song.",
    Call: "Call: rich, melodic whistles that rise and fall like a flute.",
    Whistle: "Whistle tip: play a flowing, descending melody with a bright opening note.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8f16I3KIevsvy0QcuHbZxzplaUJYYqND_4Ehyu2oEj40kBexj3Ayo95hmyrEuX_ysdHF73XFeRR4UO8okWk4ot_LH9A9bCqDc0QwK-A&s=10"
  },
  {
    id: 26,
    Common_Name: "Smith's Longspur",
    Scientific_Name: "Calcarius pictus",
    Type: "Rare",
    Season: "Summer",
    Fact: "Breeds near the treeline in northern Canada.",
    Call: "Call: light, tinkling notes with soft trills.",
    Whistle: "Whistle tip: use delicate, high whistles in short sequences, lightly trilling between notes.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXmSym08bBO_Db7pEvytYsyyO0FjBghLFgpm06nHbIOPvadpdAoOoy-x1vFOXHRwACo5JSx7kOERKv-PcRPj3134Swr5hXW2b6fXCYnA&s=10"
  },
  {
    id: 27,
    Common_Name: "Ferruginous Hawk",
    Scientific_Name: "Buteo regalis",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "The largest hawk in North America.",
    Call: "Call: long, harsh screams that trail downward.",
    Whistle: "Whistle tip: blow a sustained note and slide downward to imitate the drawn-out scream.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU5m6-BARKs-eW0lDkQq4VxS3sEYyOJStnvb6jOz0ASJ15H_jSHRmQ4OH5uofiCOA0Gx7g-YyYFRf250U35wnZUD9mPOJT1ZRHFN5vEg&s=10"
  },
  {
    id: 28,
    Common_Name: "Yellow-billed Cuckoo",
    Scientific_Name: "Coccyzus americanus",
    Type: "Rare",
    Season: "Summer",
    Fact: "Called the 'Rain Crow' for calling before storms.",
    Call: "Call: hollow 'kowlp' notes and rapid 'ka-ka-ka' series.",
    Whistle: "Whistle tip: play a hollow two-note 'kowlp-kowlp', then add a quick rattle of short notes.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmkZJ2iQebznxPAVu3PNX-YCDlfoC0AX31_Ke7dORA4rv-XgGHl2K7jpLvKBQhiDtAnG_zan7MFH9BA69OPkUhZaWOsJeX2Y8yOe9mmg&s=10"
  },
  {
    id: 29,
    Common_Name: "Prothonotary Warbler",
    Scientific_Name: "Protonotaria citrea",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Nests in cavities in standing water swamps.",
    Call: "Call: ringing 'sweet-sweet-sweet' notes, clear and even.",
    Whistle: "Whistle tip: use three to five bright, even notes on the same pitch.",
    Image: "https://upload.wikimedia.org/wikipedia/commons/5/55/Protonotaria-citrea-002_edit.jpg"
  },
  {
    id: 30,
    Common_Name: "Least Bittern",
    Scientific_Name: "Ixobrychus exilis",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "A tiny heron that hides in dense reeds.",
    Call: "Call: soft, repetitive 'coo' or 'kuk' notes from cover.",
    Whistle: "Whistle tip: play low, gentle notes with long pauses to suggest a hidden caller.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKeYAzk8fU_h6uwCkSFS_wO3c2BAqbfErQ2GZ6JBlTjZH0wBbavYpFwi_PHPgOrAuH6hHSWSAB_1nYiQqqLLZK6EQILeVhGdQVtaJxUg&s=10"
  },
  {
    id: 31,
    Common_Name: "Say's Phoebe",
    Scientific_Name: "Sayornis saya",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Prefers dry, open country and badlands.",
    Call: "Call: clear two-note 'sayy-ee' or 'phoebe' phrase.",
    Whistle: "Whistle tip: play two notes with the second falling slightly in pitch.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6-WOVU6pVuTeOkdKFPkbBgKzcXH3HI9WGilEb1qV-FC9teRgpUKRF9P5HtTRhm8ZEKcR_3dJ3q0lSmzIY5zkOxBYKOFXp56TpW3le8g&s=10"
  },
  {
    id: 32,
    Common_Name: "Great Egret",
    Scientific_Name: "Ardea alba",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "A large, elegant white heron.",
    Call: "Call: low, harsh croaks and grating notes.",
    Whistle: "Whistle tip: use rough, short notes—less musical, more guttural in rhythm.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG2TqTyZ8j-6KlZzAf9Z-MaqLVoBOS7CV1lKr58EuRMe_BBx_dQaUUJZuLeTAnNZGkjAVrpLblP61PORRLI__WQGEzWAh_D3IaV8rUrQ&s=10"
  },
  {
    id: 33,
    Common_Name: "King Rail",
    Scientific_Name: "Rallus elegans",
    Type: "Rare",
    Season: "Summer",
    Fact: "The largest North American rail.",
    Call: "Call: rapid 'kik-kik-kik' or 'chack' series that accelerates.",
    Whistle: "Whistle tip: start with spaced notes, then tighten them into a fast, rattling run.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB2EwHJro9PTNuKEu1W28ICyY8-W5bISDaKwWOAZOel0BGf1fjJfLizWHmXsUZDI3mcuAT712HfU6jjNquTWlCobKeII3GXg2kfsA9TxU&s=10"
  },
  {
    id: 34,
    Common_Name: "Red-headed Woodpecker",
    Scientific_Name: "Melanerpes erythrocephalus",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "One of the few woodpeckers that catches insects in air.",
    Call: "Call: sharp 'tchur' notes and rapid drum rolls.",
    Whistle: "Whistle tip: hit a sharp note, then follow with a quick staccato burst to suggest drumming.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMyOdABzYtm7QGQ7SwDOJBBtzMoCzWKs3SV4sWjmyO5pIfh4_kNHWdSmrALV5THUNULnJR6qDeKUtPzyg2-FQZZR4-PFg_lh7jYRadsA&s=10"
  },
  {
    id: 35,
    Common_Name: "Long-billed Curlew",
    Scientific_Name: "Numenius americanus",
    Type: "Rare",
    Season: "Spring/Summer",
    Fact: "Has a ridiculously long, down-curved bill.",
    Call: "Call: long, bubbling whistle often rendered as 'cur-lee'.",
    Whistle: "Whistle tip: play a long note that rises slightly then falls, repeating with a liquid quality.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ5Ix_DiXeLcap5RZSCRBfDOsxC-Q6jOpZoaJG3bf1hPUB3LX5r18EYWggTlx7cwbfOsMAKG4BMvl5s_hOAs7QjMapmEdmFk-rYA1J3w&s=10"
  },
  {
    id: 36,
    Common_Name: "Ivory Gull",
    Scientific_Name: "Pagophila eburnea",
    Type: "Ultra Rare",
    Season: "Winter",
    Fact: "Pure white gull of the high Arctic.",
    Call: "Call: high 'kek' or yelping notes similar to other gulls.",
    Whistle: "Whistle tip: use short, high notes in pairs or triplets with a slight nasal edge.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgYRbu40b2WIXwsmMSennOEh8RnxXrORjrWDzoQ0BoMRSN5nHQ-bi5Hur9qkvLp7jVaxk28JfcLnwQIy7PJHwmQlKOGLrz45Hs2Be3Hw&s=10"
  },
  {
    id: 37,
    Common_Name: "Gyrfalcon",
    Scientific_Name: "Falco rusticolus",
    Type: "Ultra Rare",
    Season: "Winter",
    Fact: "The largest falcon in the world.",
    Call: "Call: sharp, repetitive 'kak-kak' or 'kee' notes.",
    Whistle: "Whistle tip: play a firm, high note repeated in quick bursts, slightly descending.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDvd7O3GZB82aPodJC-tAaqR_Mn-S3dSoK36ask8xm1DRDzTcKsuIWcpRvyWkAi5er5m7m5edBAiJlvgjS_pkAkflwh7S0IU_7HQBN370&s=10"
  },
  {
    id: 38,
    Common_Name: "Whooping Crane",
    Scientific_Name: "Grus americana",
    Type: "Ultra Rare",
    Season: "Migration",
    Fact: "One of the rarest birds in North America.",
    Call: "Call: loud, trumpeting bugle with a rising start and falling finish.",
    Whistle: "Whistle tip: play a long, clear rising note, then drop slightly to finish the bugle.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQAfzifwmZfEg3UKup1IT6WZ6My1otkAS0ctDuKtbTxyBa7Llv2lc_001UNQjPW9rB0P9ffUo95yfCx8H30BSyZt35YEum_u77CQrxmA&s=10"
  },
  {
    id: 39,
    Common_Name: "Ross's Gull",
    Scientific_Name: "Rhodostethia rosea",
    Type: "Ultra Rare",
    Season: "Winter",
    Fact: "Known for having pinkish underparts.",
    Call: "Call: high, thin 'kik' notes and soft gull-like mews.",
    Whistle: "Whistle tip: use quick, high notes in short bursts, keeping them light and airy.",
    Image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9XgF0uY7ElkmsLAC-gZLZryOR7QqLRHbkytl2Tr6X9a30Vcz_Tdrt4GnQg5A4ICIf5eT5swg0h7LKuTCHKFhRuZ-E5ftuVQvOAvWP8Q&s=10"
  },
  {
    id: 40,
    Common_Name: "Kirtland's Warbler",
    Scientific_Name: "Setophaga kirtlandii",
    Type: "Ultra Rare",
    Season: "Summer",
    Fact: "Nests only in young jack pine forests.",
    Call: "Call: loud, rhythmic 'chip-chip-chee' song with a rising feel.",
    Whistle: "Whistle tip: play two short notes followed by a slightly higher, longer note.",
    Image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Dendroica_kirtlandii_-Michigan%2C_USA_-male-8_%285%29.jpg/500px-Dendroica_kirtlandii_-Michigan%2C_USA_-male-8_%285%29.jpg"
  }
];
